services:
    _defaults:
        autowire: true
        autoconfigure: true

    EonX\EasySecurity\Bridge\Symfony\Security\ContextAuthenticator: ~

    EonX\EasySecurity\Bridge\Symfony\Interfaces\AuthenticationFailureResponseFactoryInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Factories\AuthenticationFailureResponseFactory

    EonX\EasySecurity\Interfaces\ContextFactoryInterface:
        class: EonX\EasySecurity\ContextFactory

    EonX\EasySecurity\Interfaces\ContextResolverInterface:
        class: EonX\EasySecurity\ContextResolver

    EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredContextResolverInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Helpers\DeferredContextResolver
